### ISSUE TITLE
Notification is cleared when app is paused

### ISSUE THREAD

**Issue by varepato** [DavidBriglio/cordova-plugin-local-notifications#3]
**Expected behavior**

- When clicked a button a notification should be shown. 
- The notification should be cleared when the button is clicked again.
- The notification should persist if the app is paused. 

**Actual behavior**

- The notification gets cleared when the app is paused. 
- When the app is in foreground and try to change app the notification clears itself.

**Platform**

- Ionic v1. 
- Android 5.1
- Huawei Mate S

**Code**
```
  function localNotify(){
    if(!vm.showAlert){
      var date = new Date();
      cordova.plugins.notification.local.schedule({
          id: 5,
          title: "Panic Button",
          message: "Panic Button is Active",
          firstAt: date
      });
      cordova.plugins.notification.local.on("click", function (notification) {
          $state.go('panicButton');
      });
    }
  }
```

**Comment by DavidBriglio** [comment]
Are you using the plugin "phonegap-plugin-push" as well? I have noticed this behaviour when I have these two plugins included in the same project.

**Comment by varepato** [comment]
Yes i am using it. Any push plugin you recommend? 
The solution i found was to install this plugin https://github.com/katzer/cordova-plugin-background-mode
So i can show a notification in background mode.

**Comment by DavidBriglio** [comment]
Using this [this push plugin](https://github.com/fechanique/cordova-plugin-fcm/tree/master/src/ios) works for me, but it doesn't provide a callback when the notification is received in the background (it creates a notification instead). I am trying to find a solution that does not require having your application constantly run in the background.

**Comment by varepato** [comment]
Thanks a lot for helping me. Does that plugin works with amazon SNS?

**Comment by DavidBriglio** [comment]
That one is only for FCM.

**Comment by varepato** [comment]
Then, for now i'm going to keep push plugin and background mode. :/ 
Thank you for helping me.
