### ISSUE TITLE
ionic 2 on click notification become in background mode

### ISSUE THREAD

**Issue by kirajhpang** [DavidBriglio/cordova-plugin-local-notifications#4]
Hi, I no sure this is should be relate to this plugin issue or not. 

I using FCM for getting notification, and use local notification service to print notification if user receive in foreground. The issue now is, if user try to click the notification in foreground, ionic can do Nav.push() action to navigate user directly to specific page. 

one situation I notice is when user click notification, debug console show: background mode is activate. 

Any solution regarding this?

**Comment by DavidBriglio** [comment]
I'm not quite sure what issue you are having, but I know that there are a lot of issues when using both this plugin and [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push). One issue in particular is push notifications being handled by the local notification plugin.

I would recommend using [cordova-plugin-fcm](https://github.com/fechanique/cordova-plugin-fcm) with this plugin, or using [my own fork of cordova-plugin-fcm](https://github.com/DavidBriglio/cordova-plugin-fcm).

If this does not solve your issue, please post more details about what is going wrong. Unfortunately if it is an issue with Ionic itself, I have never used it and would not be able to help with that side of the problem.

**Comment by kirajhpang** [comment]
I think I know the reason, because I calling `Nav` from service, it seem like ionic doesn't allow to do so. 

I forced to push all my FCM notification listener in `app.component.ts`(which suppose is top-most controller) and use [native local notification typescript](https://ionicframework.com/docs/native/local-notifications/) to caught click event instead of using Cordova. 

This issue can close already, thanks.
