### ISSUE TITLE
unable to add plugin

### ISSUE THREAD

**Issue by ikishanoza** [DavidBriglio/cordova-plugin-local-notifications#5]
I am trying to add this plugin via ionic CLI using ionic cordova plugin add https://github.com/DavidBriglio/cordova-plugin-local-notifications but unable to add and getting this error 

![error](https://user-images.githubusercontent.com/18045135/46395525-45d53080-c70a-11e8-9651-ea808ad100f9.png)
 any idea ? how to fix this

**Comment by DavidBriglio** [comment]
Try using https://github.com/DavidBriglio/cordova-plugin-local-notifications.git instead and see if this works (note the '.git' ending).

**Comment by ikishanoza** [comment]
same error :( 
![capture](https://user-images.githubusercontent.com/18045135/46415208-628d5a80-c742-11e8-8e58-aebfba0efaae.PNG)

**Comment by DavidBriglio** [comment]
Are you using the newest version of git and ionic?

**Comment by ikishanoza** [comment]
Not newest but ionic cli verion is 3.19.1 and cordova 8.0

**Comment by DavidBriglio** [comment]
I am not sure why this would be happening, it works for me using cordova cli 8.1.1. Maybe try updating to the latest ionic version. I have not tried this in ionic.

**Comment by ikishanoza** [comment]
Okay sure will do that and let u know..thanks for your time man
