### ISSUE TITLE
Are repeating notifications reliable?

### ISSUE THREAD

**Issue by halindrome** [DavidBriglio/cordova-plugin-local-notifications#6]
This is really a question, not an issue.   

I have been using the katzer master version of this plugin, and one problem we seem to run into is that a repeating notification on Android (6, 7, 8) will only play once or twice, and then stop.   

Does anyone know if the repeating functionality is working in this fork?

For example, a notification like:

```
{
          id: 2,
          title: "sometitle",
          foreground: true,
          text: "my text",
          sound: device.platform === 'iOS' ? "file://Klaxon_horn.caf" : "file://Klaxon_horn.mp3",
          vibrate: 6000,
          data: { target: "location" },
          trigger: { every: 'minute' }
}
``` 

I would expect this to play my custom sound every minute until the notification was acknowledged.

**Comment by DavidBriglio** [comment]
This fork does not change that behaviour from the original repository. If this is an issue with the original repository, it will have the same behaviour in this fork. You may want to consider opening an issue in that repository as well.
